baseurl      = "iqltd.org/"
title        = "Valentin Musoiu"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Commito, ergo sum"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Personal blog"
  keywords = "homepage, blog"
  images = [""]

[[params.social]]
  url   = "https://linkedin.com/in/iqltd"
  icon  = "linkedin-in" # icon name without the 'fa-'
  icon_pack = "fab"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/iqltd"

[[params.social]]
  name = "github"
  url = "https://github.com/iqltd"

[[params.social]]
  name = "leetcode"
  url = "https://leetcode.com/iqltd/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Valentin Musoiu"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params]
      subtitle = "Commito, ergo sum"
      keywords = ""
      readOtherPosts = "Read other posts"
    [languages.en.params.logo]
      logoText = "/home/iqltd"
      logoHomeLink = "/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
